name: upheav_src
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  flare_flutter: any
  simple_animations: ^2.2.1
  provider: ^4.3.2
  page_transition: ^1.1.6
  fluttertoast: ^7.0.2
  shared_preferences: ^0.5.8
  sqflite:
  path:
  flutter_screenutil: ^2.3.1
  intl: ^0.16.1
  flutter_svg: ^0.18.0
  supercharged: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^1.1.0+1

flutter:
  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-BlackItalic.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-BoldItalic.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-ExtraBold.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-ExtraBoldItalic.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Italic.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Medium.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-MediumItalic.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-SemiBold.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-SemiBoldItalic.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
        
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf

  uses-material-design: true
  assets:
    - assets/images/
    - assets/flare/